export const siteAuthCopy = {
  en: {
    home: "Back home",
    download: "Download desktop",
    legalNoticeLead: "By continuing, you agree to the",
    legalNoticeJoin: "and",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    introLabel: "Secure account access",
    introBody: "A quieter, more focused account flow for signing in, creating your account, or recovering access.",
    desktopLabel: "Opened from desktop",
    desktopTitle: "Finish this step here, then return to MotiClaw Desktop.",
    desktopBody: "If this page was opened from the app, we will return you there automatically after success.",
    websiteLabel: "Website account access",
    websiteTitle: "Use one account across the website and desktop.",
    websiteBody: "Use the same email in both places so your account status and recovery steps stay aligned.",
    providerDivider: "or",
    watchaLoginAction: "Continue with Watcha",
    watchaLoginRedirecting: "Opening Watcha…",
    stepsLabel: "What happens next",
    steps: [
      { title: "Use one email", body: "Create your MotiClaw account here or log in with the email you already use." },
      { title: "Finish this step", body: "The main action, the switch link, and any recovery path stay in one clear place." },
      { title: "Return with context", body: "If you came from MotiClaw Desktop, we will hand you back there automatically after success." },
    ],
    desktopReturn: {
      actionHint: "If MotiClaw Desktop does not open automatically, use the button below to continue there.",
      retryAction: "Retry returning to desktop",
      blockedTitle: "Your browser is currently blocking this website from reconnecting to MotiClaw Desktop.",
      blockedBody: "Open the site controls next to the address bar, change Apps on your device to Allow or Ask, then retry.",
      blockedSteps: [
        "Click the site info controls next to the address bar.",
        "Change Apps on your device from Block to Allow or Ask.",
        "Keep MotiClaw Desktop open, then retry returning to the app.",
      ],
      failedTitle: "This step finished, but MotiClaw Desktop did not reconnect yet.",
      failedBody: "Make sure the desktop app is still open. If your browser blocked device access earlier, allow it first, then retry.",
    },
    alreadySignedIn: {
      eyebrow: "Account ready",
      title: "You're already signed in on the website.",
      confirmBody: "We're ready to return you to MotiClaw Desktop. If it does not open automatically, use the button below to continue there.",
      websiteBody: "This website is already signed in with your account. You can head to MotiClaw Desktop now, or sign out and use another email.",
      continueAction: "Open MotiClaw to continue",
      websiteAction: "Go to MotiClaw Desktop",
      switchAccountAction: "Use another account",
      successTitle: "This account is confirmed.",
      successBody: "Returning to MotiClaw Desktop now.",
      returning: "Returning to MotiClaw Desktop…",
      logout: "Sign out",
    },
    registerVerification: {
      sentBody: "We sent a verification code to this email. Enter it here to finish creating your account.",
      resentBody: "We sent a fresh verification code.",
      verifyAction: "Verify email",
      verifying: "Verifying…",
      resendAction: "Resend code",
      editAction: "Change email",
      previewCodePrefix: "Local debug code: ",
    },
    modes: {
      login: {
        eyebrow: "Account login",
        title: "Welcome back",
        body: "Sign in with your email and password.",
        submit: "Log in",
        submitting: "Logging in…",
        successTitle: "You're signed in.",
        successBody: "Returning to MotiClaw Desktop now.",
        footerLead: "Need an account?",
        footerAction: "Create one",
        sideActionLabel: "Forgot password?",
      },
      register: {
        eyebrow: "Create account",
        title: "Create your account",
        body: "Use your email to create a MotiClaw account. We will verify the email before the account is created.",
        submit: "Send verification code",
        submitting: "Sending…",
        successTitle: "Account created.",
        successBody: "Returning to MotiClaw Desktop now.",
        footerLead: "Already have an account?",
        footerAction: "Log in",
        sideActionLabel: "Open login",
      },
      "forgot-password": {
        eyebrow: "Reset access",
        title: "Forgot your password?",
        body: "Enter your email and we will send you the next step.",
        submit: "Send reset link",
        submitting: "Sending…",
        successTitle: "Check your email.",
        successBody: "If this email is registered, we've sent a reset link. After you set a new password, go back to MotiClaw Desktop and log in again.",
        footerLead: "Remember your password?",
        footerAction: "Back to login",
        sideActionLabel: "Create account",
      },
      "reset-password": {
        eyebrow: "Set new password",
        title: "Set a new password",
        body: "Save a new password, then use it the next time you sign in.",
        submit: "Save new password",
        submitting: "Saving…",
        successTitle: "Password updated.",
        successBody: "Use the new password when you return to MotiClaw Desktop.",
        footerLead: "Need a fresh reset link?",
        footerAction: "Open forgot password",
        sideActionLabel: "Back to login",
      },
    },
    fields: {
      displayName: "Name",
      displayNamePlaceholder: "Your name",
      email: "Email",
      emailPlaceholder: "Your email address",
      password: "Password",
      passwordPlaceholder: "Your password",
      confirmPassword: "Confirm password",
      confirmPasswordPlaceholder: "Enter your password again",
      newPassword: "New password",
      newPasswordPlaceholder: "Your new password",
      resetToken: "Reset link code",
      resetTokenPlaceholder: "Paste the code from your reset link",
      emailVerificationCode: "Email verification code",
      emailVerificationCodePlaceholder: "Enter the 6-digit code",
    },
    passwordVisibility: {
      show: "Show password",
      hide: "Hide password",
    },
    previewReset: "Open reset link preview",
    resetTokenReady: "Reset link detected",
    errors: {
      client_email_required: "Enter your email first.",
      client_password_required: "Enter your password first.",
      client_password_confirmation_required: "Enter your password again to confirm it.",
      client_password_mismatch: "The two passwords do not match yet.",
      client_verification_code_required: "Enter the email verification code first.",
      client_new_password_required: "Enter your new password first.",
      client_reset_token_required: "Open the reset link from your email, or paste the reset code here.",
      auth_password_too_short: "Your password must be at least 8 characters.",
      auth_email_invalid: "Enter a valid email address.",
      auth_invalid_credentials: "That email or password doesn't match.",
      auth_email_already_registered: "This email is already registered. Log in instead.",
      auth_email_not_verified: "Verify your email before logging in.",
      auth_registration_code_invalid: "That verification code is not correct. Check the email and try again.",
      auth_registration_code_expired: "That verification code has expired. Send a new one and try again.",
      auth_registration_pending_missing: "Send a verification code before continuing.",
      auth_account_disabled: "This account is not available right now. Please contact support.",
      auth_email_delivery_not_configured: "Email delivery is not ready yet. Please contact support.",
      auth_email_delivery_failed: "The email could not be sent right now. Please try again later.",
      auth_rate_limited: "Too many attempts for now. Please try again later.",
      auth_reset_token_invalid: "This reset link has expired. Request a new one.",
      turnstile_required: "Complete the security check first.",
      turnstile_rejected: "The security check did not pass. Please try again.",
      turnstile_verify_failed: "The security check is temporarily unavailable. Please try again shortly.",
      turnstile_response_invalid: "The security check returned an unexpected result. Please try again.",
      turnstile_network_limited: "Your current network may be limiting the security check. Try switching networks or refreshing the page.",
      invalid_client_redirect_uri: "The return link to MotiClaw Desktop is not available. Please reopen the auth page from the app.",
      desktop_return_blocked: "This step finished on the website, but your browser is blocking the return to MotiClaw Desktop.",
      site_auth_session_missing: "The website session is no longer available. Please sign in again.",
      desktop_return_failed: "This step finished on the website, but MotiClaw Desktop did not reconnect automatically. Make sure the app is still open, then go back to the desktop app and select Sign In again.",
      oauth_access_denied: "Watcha sign-in was cancelled. You can try again whenever you're ready.",
      oauth_authorization_url_missing: "Watcha sign-in is not ready yet. Please try again later.",
      oauth_code_missing: "Watcha did not return the sign-in confirmation. Please try again.",
      oauth_provider_error: "Watcha sign-in did not finish this time. Please try again later.",
      oauth_provider_request_failed: "Watcha sign-in is temporarily unavailable. Please try again shortly.",
      oauth_state_invalid: "This Watcha sign-in session has expired. Please start again.",
      auth_provider_not_configured: "Watcha sign-in is not ready yet. Please use email login for now.",
      auth_provider_secret_not_configured: "Watcha sign-in is not ready yet. Please use email login for now.",
      site_auth_http_502: "The account service is temporarily unavailable. Please try again shortly.",
    },
  },
  zh: {
    home: "返回首页",
    download: "下载桌面端",
    legalNoticeLead: "继续即表示你同意",
    legalNoticeJoin: "和",
    termsOfService: "《服务条款》",
    privacyPolicy: "《隐私政策》",
    introLabel: "安全账号入口",
    introBody: "把登录、注册和找回密码这一步收得更聚焦，让你第一眼就知道该在哪里继续。",
    desktopLabel: "从桌面端打开",
    desktopTitle: "先在这里完成这一步，然后回到 MotiClaw Desktop。",
    desktopBody: "如果这个页面是从 App 打开的，成功后我们会自动把你带回桌面端继续。",
    websiteLabel: "官网账号入口",
    websiteTitle: "官网和桌面端用同一个账号就可以。",
    websiteBody: "用同一个邮箱登录官网和桌面端，这样账号状态和找回密码流程都会保持一致。",
    providerDivider: "或",
    watchaLoginAction: "使用观猹登录",
    watchaLoginRedirecting: "正在打开观猹…",
    stepsLabel: "接下来会发生什么",
    steps: [
      { title: "先用同一个邮箱", body: "在这里创建 MotiClaw 账号，或者直接登录你已经在用的邮箱账号。" },
      { title: "这一步集中完成", body: "主按钮、切换入口和找回路径会被放在同一个清晰区域里。" },
      { title: "带着上下文返回", body: "如果你是从 MotiClaw Desktop 过来的，成功后我们会自动把你带回去继续。" },
    ],
    desktopReturn: {
      actionHint: "如果 MotiClaw Desktop 没有自动打开，可以点下面的按钮继续使用。",
      retryAction: "重试返回桌面端",
      blockedTitle: "浏览器当前阻止了这个网页重新连接 MotiClaw Desktop。",
      blockedBody: "请打开地址栏左侧的网站信息，把“设备上的应用”改成“允许”或“询问(默认)”，然后再试一次。",
      blockedSteps: [
        "点击地址栏左侧的网站信息图标。",
        "把“设备上的应用”从“阻止”改成“允许”或“询问(默认)”。",
        "确认 MotiClaw Desktop 仍然开着，然后重试返回桌面端。",
      ],
      failedTitle: "这一步已经完成，但 MotiClaw Desktop 还没有重新连上。",
      failedBody: "请确认桌面端 App 仍然开着。如果浏览器之前拦过设备访问，请先允许，再重试一次。",
    },
    alreadySignedIn: {
      eyebrow: "账号已就绪",
      title: "你已经在官网登录。",
      confirmBody: "我们已经准备把你带回 MotiClaw Desktop 继续刚才那一步；如果没有自动打开，可以直接点下面的按钮继续。",
      websiteBody: "当前官网已经是这个账号登录状态。你现在可以直接前往 MotiClaw 客户端，或者先退出再换一个邮箱。",
      continueAction: "打开 MotiClaw 继续使用",
      websiteAction: "前往 MotiClaw 客户端",
      switchAccountAction: "切换账号",
      successTitle: "当前账号已确认。",
      successBody: "正在返回 MotiClaw Desktop。",
      returning: "正在返回 MotiClaw Desktop…",
      logout: "退出登录",
    },
    registerVerification: {
      sentBody: "验证码已经发送到这个邮箱。请输入验证码后再创建账号。",
      resentBody: "新的验证码已经发送。",
      verifyAction: "验证邮箱",
      verifying: "验证中…",
      resendAction: "重新发送",
      editAction: "修改邮箱",
      previewCodePrefix: "本地调试验证码：",
    },
    modes: {
      login: {
        eyebrow: "账号登录",
        title: "欢迎回来",
        body: "输入邮箱和密码登录。",
        submit: "登录",
        submitting: "登录中…",
        successTitle: "已经登录。",
        successBody: "正在返回 MotiClaw Desktop。",
        footerLead: "还没有账号？",
        footerAction: "去注册",
        sideActionLabel: "忘记密码？",
      },
      register: {
        eyebrow: "创建账号",
        title: "创建账号",
        body: "用邮箱创建你的 MotiClaw 账号。账号创建前需要先完成邮箱验证。",
        submit: "发送验证码",
        submitting: "发送中…",
        successTitle: "账号已创建。",
        successBody: "正在返回 MotiClaw Desktop。",
        footerLead: "已经有账号？",
        footerAction: "去登录",
        sideActionLabel: "打开登录页",
      },
      "forgot-password": {
        eyebrow: "找回密码",
        title: "忘记密码了？",
        body: "输入邮箱，我们会把下一步发到这个邮箱里。",
        submit: "发送重置链接",
        submitting: "发送中…",
        successTitle: "请查收邮箱。",
        successBody: "如果这个邮箱已经注册，我们已经把重置链接发过去了。改好密码后，再回到 MotiClaw Desktop 登录。",
        footerLead: "想起来了？",
        footerAction: "回到登录",
        sideActionLabel: "去注册",
      },
      "reset-password": {
        eyebrow: "设置新密码",
        title: "设置新密码",
        body: "保存新密码后，下次登录时就可以使用。",
        submit: "保存新密码",
        submitting: "保存中…",
        successTitle: "密码已更新。",
        successBody: "回到 MotiClaw Desktop 后，请用新密码继续登录。",
        footerLead: "需要重新发重置链接？",
        footerAction: "打开找回密码",
        sideActionLabel: "回到登录",
      },
    },
    fields: {
      displayName: "称呼",
      displayNamePlaceholder: "你的名字",
      email: "邮箱",
      emailPlaceholder: "你的邮箱地址",
      password: "密码",
      passwordPlaceholder: "你的密码",
      confirmPassword: "确认密码",
      confirmPasswordPlaceholder: "再输入一次密码",
      newPassword: "新密码",
      newPasswordPlaceholder: "你的新密码",
      resetToken: "重置链接里的验证码",
      resetTokenPlaceholder: "从邮件里的重置链接复制验证码",
      emailVerificationCode: "邮箱验证码",
      emailVerificationCodePlaceholder: "输入 6 位验证码",
    },
    passwordVisibility: {
      show: "显示密码",
      hide: "隐藏密码",
    },
    previewReset: "打开调试重置链接",
    resetTokenReady: "已识别重置链接",
    errors: {
      client_email_required: "请先输入邮箱。",
      client_password_required: "请先输入密码。",
      client_password_confirmation_required: "请再输入一次密码。",
      client_password_mismatch: "两次输入的密码不一致，请检查后重试。",
      client_verification_code_required: "请先输入邮箱验证码。",
      client_new_password_required: "请先输入新密码。",
      client_reset_token_required: "请从邮件里的重置链接进入，或者把验证码贴到这里。",
      auth_password_too_short: "密码至少需要 8 个字符。",
      auth_email_invalid: "请输入有效的邮箱地址。",
      auth_invalid_credentials: "邮箱或密码不正确。",
      auth_email_already_registered: "这个邮箱已经注册过了，直接登录就可以。",
      auth_email_not_verified: "请先完成邮箱验证，再登录。",
      auth_registration_code_invalid: "邮箱验证码不正确，请检查后再试。",
      auth_registration_code_expired: "邮箱验证码已经过期，请重新发送。",
      auth_registration_pending_missing: "请先发送邮箱验证码，再继续。",
      auth_account_disabled: "这个账号暂时不可用，请联系支持处理。",
      auth_email_delivery_not_configured: "邮件发送还没有准备好，请联系支持处理。",
      auth_email_delivery_failed: "邮件暂时发送失败，请稍后再试。",
      auth_rate_limited: "当前尝试次数有点多，请稍后再试。",
      auth_reset_token_invalid: "这个重置链接已经失效，请重新发起找回密码。",
      turnstile_required: "请先完成安全验证。",
      turnstile_rejected: "安全验证没有通过，请再试一次。",
      turnstile_verify_failed: "安全验证服务暂时不可用，请稍后再试。",
      turnstile_response_invalid: "安全验证返回异常，请稍后再试。",
      turnstile_network_limited: "当前网络可能限制安全验证，请尝试切换网络或刷新页面。",
      invalid_client_redirect_uri: "返回 MotiClaw Desktop 的链接不可用，请重新从 App 打开这个账号页。",
      desktop_return_blocked: "这一步已经在官网完成，但浏览器正在阻止返回 MotiClaw Desktop。",
      site_auth_session_missing: "当前网页登录态已经失效，请重新登录。",
      desktop_return_failed: "这一步已经在官网完成，但还没能自动回到 MotiClaw Desktop。请确认 App 仍然开着，然后回到桌面端再点一次登录。",
      oauth_access_denied: "观猹登录已取消。准备好后可以再试一次。",
      oauth_authorization_url_missing: "观猹登录暂时还没准备好，请稍后再试。",
      oauth_code_missing: "观猹没有返回登录确认，请重新试一次。",
      oauth_provider_error: "这次观猹登录没有完成，请稍后再试。",
      oauth_provider_request_failed: "观猹登录暂时不可用，请稍后再试。",
      oauth_state_invalid: "这次观猹登录已过期，请重新发起登录。",
      auth_provider_not_configured: "观猹登录暂时还没准备好，请先使用邮箱登录。",
      auth_provider_secret_not_configured: "观猹登录暂时还没准备好，请先使用邮箱登录。",
      site_auth_http_502: "账号服务暂时不可用，请稍后再试。",
    },
  },
} as const;
