import { siteBillingCopy, type SiteBillingCopy } from "@/components/site-billing-copy";

export type SitePointsCopy = SiteBillingCopy;

export const sitePointsCopy: Record<"en" | "zh", SitePointsCopy> = {
  en: {
    ...siteBillingCopy.en,
    eyebrow: "Points center",
    title: "Points recharge",
    intro: "Top up points for pay-as-you-go capabilities. Your new balance is available as soon as payment is confirmed.",
    signedOutBody: "You can review the points packages first. Sign in when you're ready to recharge.",
    unavailable: "Points recharge is temporarily unavailable. Please try again later.",
    choosePlan: "Points packages",
    createOrder: "Recharge now",
    continuePayment: "Continue payment",
    paymentSectionTitle: "WeChat recharge",
    scanTitle: "Scan to recharge",
    scanBody: "Use WeChat to scan this QR code. This page checks the payment automatically and updates your balance when the points arrive.",
    paymentSuccessTitle: "Recharge successful",
    paymentSuccessBody: "Your points have arrived. You can return to MotiClaw and continue the same task.",
    paidTitle: "Points have arrived",
    paidBody: "The points from this order are now available in your account.",
    recentLedger: "Points activity",
    recentOrders: "Recharge orders",
    emptyOrders: "No recharge orders yet",
    tipsBody: "Points pay for usage-based capabilities. Membership plans and points packages are purchased separately.",
    errors: {
      ...siteBillingCopy.en.errors,
      subscription_plan_not_found: "This points package is not available. Refresh and choose again.",
      site_billing_http_502: "The points recharge service is temporarily unavailable. Please try again shortly.",
    },
  },
  zh: {
    ...siteBillingCopy.zh,
    eyebrow: "积分中心",
    title: "积分充值",
    intro: "补充按量能力所需的积分。支付确认后，新的积分余额会立即可用。",
    signedOutBody: "你可以先查看积分包，准备充值时再登录。",
    unavailable: "积分充值暂时不可用，请稍后再试。",
    choosePlan: "积分包",
    createOrder: "立即充值",
    continuePayment: "继续支付",
    paymentSectionTitle: "微信充值",
    scanTitle: "扫码充值",
    scanBody: "请用微信扫描二维码完成支付。本页会自动确认支付状态，积分到账后同步更新余额。",
    paymentSuccessTitle: "充值成功",
    paymentSuccessBody: "积分已经到账，可以回到 MotiClaw 继续刚才的任务。",
    paidTitle: "积分已到账",
    paidBody: "这笔订单的积分已经可以使用。",
    recentLedger: "积分明细",
    recentOrders: "充值订单",
    emptyOrders: "还没有充值订单",
    tipsBody: "积分用于按量能力消耗。会员套餐和积分包分别购买，互不影响。",
    errors: {
      ...siteBillingCopy.zh.errors,
      subscription_plan_not_found: "这个积分包暂不可用，请刷新后重新选择。",
      site_billing_http_502: "积分充值服务暂时不可用，请稍后再试。",
    },
  },
};
